services:
  - type: web
    name: digital-noc-system
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build:frontend
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        value: https://digital-noc-system.onrender.com
      - key: PORT
        value: 10000